[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.3"
itertools = "0.12.0"
pathfinding = "4.4.0"
scan_fmt = "0.2.6"
serde_scan = "0.4.1"
